// This file has been autogenerated from a class added in the UI designer.

namespace Costoda.CRM.MacOS
{
	public partial class MainWindowController 
		: NSWindowController, INSWindowDelegate
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

		public override void WindowDidLoad()
		{
			base.WindowDidLoad();
			
			var windowDelegate = new MainWindowDelegate(this);
			Window.Delegate = windowDelegate; 	
			Window.SetFrame(new CGRect(x: 100, y: 100, width: 1200, height: 800), true);
			
			WillLoad();
		}

		private void WillLoad()
		{
			tbItemMyProfile.Activated += MyProfileClicked;
		}

		public void WillClose()
		{
			this.tbItemMyProfile.Activated -= MyProfileClicked;
		}
		
		private void MyProfileClicked(object? sender, EventArgs e)
		{
			Console.WriteLine("My Profile Clicked");	
		}
	}
}
