// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Costoda.CRM.MacOS
{
	public partial class AuthBackgroundView : NSView
	{
		public AuthBackgroundView (IntPtr handle) : base (handle)
		{
		}

        public override void UpdateLayer()
        {
            base.UpdateLayer();

            if (Layer is not null)
            {
                var r = 44m / 255m;
                var b = 44m / 255m;
                var g = 44m / 255;

                Layer.BackgroundColor = new CGColor((float)r, (float)g, (float)b);
            }
        }
    }
}
