// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Costoda.CRM.MacOS
{
	public partial class AuthenticationWindowController : NSWindowController
	{
		public AuthenticationWindowController(IntPtr handle) : base(handle)
		{
		}

		public override void WindowDidLoad()
		{
			base.WindowDidLoad();
			this.Window.Center();
		}
	}
}
