// This file has been autogenerated from a class added in the UI designer.
using Costoda.CRM.MacOS.ViewControllers;

namespace Costoda.CRM.MacOS
{
	public partial class MainWindowController 
		: NSWindowController, INSWindowDelegate
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

		public override void WindowDidLoad()
		{
			base.WindowDidLoad();
			
			var windowDelegate = new MainWindowDelegate(this);
			Window.Delegate = windowDelegate; 	
			Window.SetFrame(new CGRect(x: 100, y: 100, width: 1200, height: 800), true);
			
			WillLoad();
		}

		private void WillLoad()
		{
			tbItemMyProfile.Activated += MyProfileClicked;
			tbItemCampaigns.Activated += CampaignsClicked;
			tbItemCompanies.Activated += CompaniesClicked;
			tbItemContacts.Activated += ContactsClicked;
		}

		public void WillClose()
		{
			tbItemMyProfile.Activated -= MyProfileClicked;
			tbItemCampaigns.Activated -= CampaignsClicked;
			tbItemCompanies.Activated -= CompaniesClicked;
			tbItemContacts.Activated -= ContactsClicked;
		}

		private MainSplitViewController? GetSplitViewController()
		{
			if (this.ContentViewController is MainSplitViewController)
			{
				return this.ContentViewController as MainSplitViewController;
			}

			return null;
		}

		private void ChangeViewTo(ViewOptions viewOptions)
		{
			var splitViewController = GetSplitViewController();
			if (splitViewController == null) return;
			if (splitViewController.SplitViewItems.Count() < 2) return;
			
			var mainSplitViewItem = splitViewController.SplitViewItems[0];
			var detailSplitViewItem = splitViewController.SplitViewItems[1];
			if (mainSplitViewItem.ViewController is MainViewController mainViewController  &&
			    detailSplitViewItem.ViewController is DetailViewController detailViewController)
			{
				mainViewController.ChangeView(viewOptions);	
				detailViewController.ChangeView(viewOptions);
			}
		}

		private void MyProfileClicked(object? sender, EventArgs e)
		{
			Console.WriteLine("My Profile Clicked");	
		}

		private void CompaniesClicked(object? sender, EventArgs e)
		{
			ChangeViewTo(ViewOptions.Companies);	
		}

		private void ContactsClicked(object? sender, EventArgs e)
		{
			ChangeViewTo(ViewOptions.Contacts);	
		}

		private void CampaignsClicked(object? sender, EventArgs e)
		{
			ChangeViewTo(ViewOptions.Campaigns);	
		}

	}
}
