// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Costoda.CRM.MacOS
{
	public partial class DetailViewController : NSViewController
	{
		public DetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
