// This file has been autogenerated from a class added in the UI designer.
using Costoda.CRM.MacOS.ViewControllers;

namespace Costoda.CRM.MacOS
{
	public partial class MainViewController : 
		NSViewController, IChangeViewByViewOptions
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			
			// Register the NSCollectionViewItem class and its associated XIB file
			colViewMain.RegisterNib(new NSNib("CompanyCollectionViewItem", null), "CompanyCollectionViewItem");
		}

		public void ChangeView(ViewOptions viewOptions)
		{
			Console.WriteLine($"Main View got viewOptions: {viewOptions}");
		}
	}
}
